version: '3'

services: 

  web:
    build: ./movie-service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./movie-service:/code
    ports:
      - "8000:8000"
    
  # elasticsearch:
  #   image: 'elasticsearch:5'
  #   restart: always
  #   volumes:
  #     - ./es_data:/usr/share/elasticsearch/data
  #   environment:
  #     - discovery.type=single-node
  #     - bootstrap.memory_lock=true
  #   ports:
  #     - '9200:9200'