version: '3'

services: 

  movie-service:
    build: ./movie-service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./movie-service:/code
    ports:
      - "8000:8000"

  movie-service-db:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data

#
#  kafka:
#    image:
#
#  elasticsearch:
#    image: 'elasticsearch:5'
#    restart: always
#    volumes:
#      - ./data/es_data:/usr/share/elasticsearch/data
#    environment:
#      - discovery.type=single-node
#      - bootstrap.memory_lock=true
#    ports:
#      - '9200:9200'