# Generated by Django 2.2 on 2019-04-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='list',
        ),
        migrations.AddField(
            model_name='list',
            name='movies',
            field=models.ManyToManyField(to='movie.Movies'),
        ),
    ]
